# Generated by Django 4.2 on 2024-12-11 12:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='balance_init',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
    ]
