# Generated by Django 4.2 on 2025-03-22 05:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='balance_init',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
    ]
