# Generated by Django 4.2 on 2025-02-03 12:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import return_purchases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0002_supplier_balance_supplier_balance_init'),
        ('product', '0003_product_average_cost'),
        ('warehouse', '0008_remove_centralinventory_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('is_received', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('number', models.PositiveIntegerField(default=return_purchases.models.get_next_order_number, unique=True)),
                ('undiscount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_purchase_orders', to='supplier.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_purchase_warehouse', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnPurchaseLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('discount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('return_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='return_purchases.returnpurchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnpurchaseorder',
            index=models.Index(fields=['created_at'], name='return_purc_created_d126f2_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpurchaseorder',
            index=models.Index(fields=['supplier'], name='return_purc_supplie_638d18_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpurchaseorder',
            index=models.Index(fields=['warehouse'], name='return_purc_warehou_799c16_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpurchaseline',
            index=models.Index(fields=['created_at'], name='return_purc_created_ce341a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpurchaseline',
            index=models.Index(fields=['product'], name='return_purc_product_f5e301_idx'),
        ),
    ]
