# Generated by Django 4.2 on 2025-02-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('return_purchases', '0002_alter_returnpurchaseline_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnpurchaseline',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='returnpurchaseline',
            name='return_purc_created_ce341a_idx',
        ),
        migrations.RemoveIndex(
            model_name='returnpurchaseline',
            name='return_purc_product_f5e301_idx',
        ),
    ]
