# Generated by Django 4.2 on 2025-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_purchases', '0003_alter_returnpurchaseline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnpurchaseline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='returnpurchaseline',
            index=models.Index(fields=['created_at'], name='return_purc_created_ce341a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpurchaseline',
            index=models.Index(fields=['product'], name='return_purc_product_f5e301_idx'),
        ),
    ]
