# Generated by Django 4.2 on 2025-03-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_purchases', '0004_alter_returnpurchaseline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
