# Generated by Django 4.2 on 2025-03-15 00:39

from django.db import migrations
from django.utils.timezone import localtime


def update_sale_order_date(apps, schema_editor):
    ReturnPurchaseOrder = apps.get_model("return_purchases", "ReturnPurchaseOrder")
    for instance in ReturnPurchaseOrder.objects.filter(date__isnull=True):
        instance.date = localtime(instance.created_at).date()
        instance.save(update_fields=["date"])


class Migration(migrations.Migration):

    dependencies = [
        ("return_purchases", "0005_returnpurchaseorder_date"),
    ]

    operations = [migrations.RunPython(update_sale_order_date)]
