# Generated by Django 4.2 on 2025-03-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_average_cost'),
        ('return_purchases', '0006_update_return_purchase_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchaseline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_purchase_lines', to='product.product'),
        ),
    ]
