# Generated by Django 4.2 on 2026-02-15 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('return_purchases', '0008_alter_returnpurchaseline_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnpurchaseorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='returnpurchaseorder',
            index=models.Index(fields=['created_by'], name='return_purc_created_1afcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='returnpurchaseorder',
            index=models.Index(fields=['updated_by'], name='return_purc_updated_f0bc62_idx'),
        ),
    ]
