# Generated by Django 4.2 on 2024-12-31 02:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance_init',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
    ]
