# Generated by Django 4.2 on 2024-10-27 11:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import purchases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('warehouse', '0008_remove_centralinventory_quantity'),
        ('product', '0003_product_average_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('is_received', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('number', models.PositiveIntegerField(default=purchases.models.get_next_order_number, unique=True)),
                ('undiscount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='supplier.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_warehouse', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('discount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='purchases_p_created_4baa22_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='purchases_p_supplie_810a18_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['warehouse'], name='purchases_p_warehou_ac0467_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseline',
            index=models.Index(fields=['created_at'], name='purchases_p_created_36d20a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseline',
            index=models.Index(fields=['product'], name='purchases_p_product_2b69b7_idx'),
        ),
    ]
