# Generated by Django 4.2 on 2025-03-22 05:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchaseline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='undiscount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='undiscount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
    ]
