# Generated by Django 4.2 on 2025-03-10 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0002_subscriptionplan_organisation_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='invoice_footer_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organisation_logos/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone_numbers',
            field=models.CharField(blank=True, help_text='Enter up to 4 phone numbers separated by commas.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='show_invoice_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to=settings.AUTH_USER_MODEL),
        ),
    ]
