# Generated by Django 4.2 on 2025-03-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_organisation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='logo',
        ),
    ]
