from rest_framework import serializers
from .models import *
from product.serializers import *


class WarehouseSerializerFroPurchase(serializers.ModelSerializer):
    class Meta:
        model = Warehouse
        fields = ["uuid","name"]
        
class WarehouseSerializerFroReturnPurchase(serializers.ModelSerializer):
    class Meta:
        model = Warehouse
        fields = ["uuid","name"]
        
class WarehouseSerializerFroSale(serializers.ModelSerializer):
    class Meta:
        model = Warehouse
        fields = ["uuid","name"]
        
class WarehouseSerializerFroReturnSale(serializers.ModelSerializer):
    class Meta:
        model = Warehouse
        fields = ["uuid","name"]
                
class WarehouseSerializer(serializers.ModelSerializer):
    class Meta:
        model = Warehouse
        fields = "__all__"

class WarehouseSerializerMinInfo(serializers.ModelSerializer):
    class Meta:
        model = Warehouse
        fields = ["uuid","name","location"]
# Serializer for handling create and update operations on the Warehouse model
class WarehouseCreateUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Warehouse
        fields = "__all__"  # Use all fields in the Warehouse model
   
    # Custom validation to check if a warehouse with the same name exists
    def validate_name(self, value):
        if Warehouse.objects.filter(name=value).exists():
            raise serializers.ValidationError("A warehouse with this name already exists.")
        return value
  
    # This method is called when creating a new warehouse object
    def create(self, validated_data):
        # uuid: Unique identifier for the warehouse, autogenerated
        # name: The name of the warehouse (required)
        # location: The location of the warehouse (required)

        # Add any custom logic here before saving the warehouse, if needed.
        # For example, logging or performing additional validations.
        
        return Warehouse.objects.create(**validated_data)  # Create and return new Warehouse instance

    # This method is called when updating an existing warehouse object
    def update(self, instance, validated_data):
        # instance: The existing Warehouse instance
        # validated_data: The new data that will update the warehouse

        # Update the fields individually
        instance.name = validated_data.get('name', instance.name)  # Update the name if provided
        instance.location = validated_data.get('location', instance.location)  # Update the location if provided

        # Save the updated warehouse object
        instance.save()

        # Return the updated warehouse instance
        return instance
        

class WarehouseInventorySerializer(serializers.ModelSerializer):
    product = ProductSerializerForWarehouse()
    class Meta:
        model = Inventory
        exclude = ['warehouse']

class InventorySerializer(serializers.ModelSerializer):
    product = ProductSerializerForInventory()
    class Meta:
        model = Inventory
        exclude = ['warehouse']

class CentralInventorySerializer(serializers.ModelSerializer):
    product = ProductSerializerForWarehouse()
    class Meta:
        model = CentralInventory
        fields = "__all__"
