# Generated by Django 4.2 on 2024-04-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_centralinventory_uuid_alter_inventory_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralinventory',
            name='logical_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='centralinventory',
            name='physical_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='logical_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='physical_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
