# Generated by Django 4.2 on 2024-04-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_centralinventory_logical_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='warehouse',
        ),
    ]
