# Generated by Django 4.2 on 2024-04-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_remove_inventory_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='warehouse.warehouse'),
            preserve_default=False,
        ),
    ]
