# Generated by Django 4.2 on 2024-04-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_inventory_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralinventory',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
