# Generated by Django 4.2 on 2024-04-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_centralinventory_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralinventory',
            name='quantity',
        ),
    ]
