# Generated by Django 4.2 on 2024-12-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='type',
            field=models.CharField(choices=[('payment', 'Payment'), ('purchase', 'Purchase')], default='payment', max_length=10),
        ),
    ]
