# Generated by Django 4.2 on 2025-01-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0002_alter_supplierpayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank_transfer')], default='cash', max_length=20),
        ),
    ]
