# Generated by Django 4.2 on 2025-01-21 05:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0003_supplierpayment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='new_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='old_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['amount'], name='supplier_pa_amount_11e6c3_idx'),
        ),
    ]
