# Generated by Django 4.2 on 2025-02-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('return_purchases', '0001_initial'),
        ('supplier_payment', '0004_supplierpayment_new_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='return_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_purchase_payments', to='return_purchases.returnpurchaseorder'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='type',
            field=models.CharField(choices=[('payment', 'Payment'), ('purchase', 'Purchase'), ('return_purchase', 'Return_purchase')], default='payment', max_length=20),
        ),
    ]
