# Generated by Django 4.2 on 2025-03-22 05:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_payment', '0005_supplierpayment_return_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
    ]
