# Generated by Django 4.2 on 2025-02-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_average_cost'),
        ('van', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaninventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='vaninventory',
            name='van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van', to='van.van'),
        ),
    ]
