# Generated by Django 4.2 on 2025-03-23 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_alter_product_average_cost_alter_product_cost_price_and_more'),
        ('van', '0002_alter_vaninventory_product_alter_vaninventory_van'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='van',
            name='location',
        ),
        migrations.RemoveField(
            model_name='van',
            name='make',
        ),
        migrations.RemoveField(
            model_name='van',
            name='model',
        ),
        migrations.RemoveField(
            model_name='van',
            name='user',
        ),
        migrations.RemoveField(
            model_name='van',
            name='year',
        ),
        migrations.AddField(
            model_name='van',
            name='license_plate',
            field=models.CharField(default='TEMP-PLATE', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='van',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='van',
            name='uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaninventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van_inventories', to='product.product'),
        ),
        migrations.AlterField(
            model_name='vaninventory',
            name='van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='van.van'),
        ),
        migrations.AlterUniqueTogether(
            name='vaninventory',
            unique_together={('van', 'product')},
        ),
        migrations.CreateModel(
            name='VanAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van_assignments', to=settings.AUTH_USER_MODEL)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='van.van')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'unique_together': {('van', 'start_datetime')},
            },
        ),
    ]
