# Generated by Django 4.2 on 2025-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van', '0003_remove_van_location_remove_van_make_remove_van_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('broken', 'Broken')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='van',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vanassignment',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
