# Generated by Django 4.2 on 2025-03-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van', '0004_van_status_alter_van_uuid_alter_vanassignment_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vanassignment',
            unique_together=set(),
        ),
    ]
