# Generated by Django 4.2 on 2025-03-25 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('van', '0005_alter_vanassignment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaninventory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
