# Generated by Django 4.2 on 2025-03-25 05:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van', '0006_alter_vaninventory_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaninventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
