# Generated by Django 4.2 on 2024-04-09 05:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_barcode_remove_product_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), max_digits=12, null=True),
        ),
    ]
