# Generated by Django 4.2 on 2025-03-22 05:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_average_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=12, null=True),
        ),
    ]
