# Generated by Django 4.2 on 2024-10-27 11:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0008_remove_centralinventory_quantity'),
        ('customer', '0004_alter_contact_email_alter_contact_phone'),
        ('product', '0003_product_average_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('is_received', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('number', models.PositiveIntegerField(default=sales.models.get_next_order_number, unique=True)),
                ('undiscount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='customer.customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_warehouse', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('discount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), max_digits=12, null=True)),
                ('average_cost', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), max_digits=12, null=True)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['created_at'], name='sales_saleo_created_1ca177_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['customer'], name='sales_saleo_custome_739fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['warehouse'], name='sales_saleo_warehou_630e17_idx'),
        ),
        migrations.AddIndex(
            model_name='saleline',
            index=models.Index(fields=['created_at'], name='sales_salel_created_5dacaa_idx'),
        ),
        migrations.AddIndex(
            model_name='saleline',
            index=models.Index(fields=['product'], name='sales_salel_product_bf8836_idx'),
        ),
    ]
