# Generated by Django 4.2 on 2025-03-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleline_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
