# Generated by Django 4.2 on 2025-03-15 00:24

from django.db import migrations
from django.utils.timezone import localtime


def update_order_dates(apps, schema_editor):
    SaleOrder = apps.get_model("sales", "SaleOrder")

    for order in SaleOrder.objects.filter(date__isnull=True):
        order.date = localtime(order.created_at).date()  # Convert UTC to local date
        order.save(update_fields=["date"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_saleorder_date"),
    ]

    operations = [
        migrations.RunPython(update_order_dates),
    ]
