# Generated by Django 4.2 on 2025-03-22 05:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleline',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='undiscount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='undiscount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
    ]
