# Generated by Django 4.2 on 2025-05-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_remove_centralinventory_quantity'),
        ('van', '0007_alter_vaninventory_quantity'),
        ('sales', '0006_alter_saleline_average_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='van',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_van', to='van.van'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_warehouse', to='warehouse.warehouse'),
        ),
    ]
