# Generated by Django 4.2 on 2026-02-16 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_saleorder_van_alter_saleorder_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['van'], name='sales_saleo_van_id_35f213_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['created_by'], name='sales_saleo_created_81e480_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['updated_by'], name='sales_saleo_updated_1562ce_idx'),
        ),
    ]
