"""
Django settings for skyvan project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import dj_database_url
import os
from datetime import timedelta
from django.core.management.utils import get_random_secret_key
from pathlib import Path
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-98g@)jlz^5%%b^#z4mi4v+1bjf+&8)l-&8=w$(08s*yxia!w(2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    # skyvan
    "customer",
    "expense",
    "history",
    "account",
    "product",
    "warehouse",
    "van",
    "supplier",
    "supplier_payment",
    "customer_payment",
    "contact",
    "purchases",
    "return_purchases",
    "sales",
    "return_sales",
    "analytics",
    "organisation",
    "transfer",
    # restframwork
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "django_filters",
    # Debug toolbar
    "debug_toolbar",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
        # Debug toolbar middleware
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "account.middleware.OrganisationMiddleware",
]

# settings.py

# Enable CORS to allow all origins (not recommended for production):
CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOWED_ORIGINS = [
    # Production
    "https://sky-manager.com",
    "https://www.sky-manager.com",
    # Vercel production (if you still access it directly)
    "https://skymanager-dashboard-prod.vercel.app",
    # Ngrok (for testing)
    "https://loosely-valued-badger.ngrok-free.app",
    # Local dev (frontend on port 3000)
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://0.0.0.0:3000",
]
import re

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.+\.vercel\.app$",
]
# Specify trusted origins for CSRF protection:
CSRF_TRUSTED_ORIGINS = [
    "https://sky-manager.com",
    "https://www.sky-manager.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://0.0.0.0:3000",
]


ROOT_URLCONF = "skyvan.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "skyvan.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASE_CONNECTION_DEFAULT_NAME = "default"
# TODO: For local envs will be activated in separate PR.
# We need to update docs an saleor platform.
# This variable should be set to `replica`
DATABASE_CONNECTION_REPLICA_NAME = "replica"


# # Parse the DATABASE_URL environment variable
DATABASES = {"default": dj_database_url.config(default=os.environ.get("DATABASE_URL"))}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Algiers"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "account.User"

# Custom create super user command
# Replace 'account' with the name of your app
AUTH_PASSWORD_VALIDATORS = []  # Disabling password validation for simplicity
# Replace 'account' with the name of your app
CUSTOM_SUPERUSER_COMMAND = "account.management.commands.createsuperuser.Command"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

AUTHENTICATION_BACKENDS = [
    "account.authentication.PhoneBackend",
]

SECRET_KEY = "bwoi2zimggip&f%w=z#b@btr#$h#bx5!cl9-5m4_y2^ksql2ro"
# print(get_random_secret_key())
# JWT settings
SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "USER_ID_FIELD": "phone",
    "USER_ID_CLAIM": "phone",
    "TOKEN_OBTAIN_SERIALIZER": "account.serializers.CustomTokenObtainPairSerializer",  # ✅ Use custom serializer
}


DEFAULT_DECIMAL_PLACES = 2
DEFAULT_MAX_DIGITS = 12
DEFAULT_WAREHOUSE_NAME = "Default"


SPECTACULAR_SETTINGS = {
    "TITLE": "Skyvan API",
    "DESCRIPTION": "API for managing stock purchases and inventory in the Skyvan system.",
    "VERSION": "1.0.0",
    "ENUM_NAME_OVERRIDES": {},
    # other settings
}


INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


if DEBUG:
    import socket
    # This dynamic check finds your Docker container's gateway IP
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]
    
    # Optional: Force the toolbar to show regardless of IP (for testing)
    # def show_toolbar(request):
    #     return True
    # DEBUG_TOOLBAR_CONFIG = {"SHOW_TOOLBAR_CALLBACK": show_toolbar}