# Generated by Django 4.2 on 2024-11-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ExpenseType',
        ),
    ]
