# Generated by Django 4.2 on 2024-11-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_category_expensetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='category',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='type',
        ),
    ]
