# Generated by Django 4.2 on 2024-11-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_type', to='expense.expensetype'),
        ),
    ]
