# Generated by Django 4.2 on 2024-11-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_budget_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionReconciliation',
        ),
    ]
