# Generated by Django 4.2 on 2025-04-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_budget_amount_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='type',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
