# Generated by Django 4.2 on 2025-03-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_remove_organisation_logo'),
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ORG_USER', 'Organization User'), ('ADMIN', 'Admin')], default='ORG_USER', max_length=10),
        ),
    ]
