# Generated by Django 4.2 on 2025-01-30 11:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import return_sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_average_cost'),
        ('customer', '0005_customer_balance_customer_balance_init'),
        ('warehouse', '0008_remove_centralinventory_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnSaleOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('is_received', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('number', models.PositiveIntegerField(default=return_sales.models.get_next_order_number, unique=True)),
                ('undiscount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_sale_orders', to='customer.customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_sale_warehouse', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnSaleLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('discount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscount_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), max_digits=12, null=True)),
                ('average_cost', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), max_digits=12, null=True)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('return_sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='return_sales.returnsaleorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnsaleorder',
            index=models.Index(fields=['created_at'], name='return_sale_created_4b4bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsaleorder',
            index=models.Index(fields=['customer'], name='return_sale_custome_afe9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsaleorder',
            index=models.Index(fields=['warehouse'], name='return_sale_warehou_51689d_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsaleline',
            index=models.Index(fields=['created_at'], name='return_sale_created_05d034_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsaleline',
            index=models.Index(fields=['product'], name='return_sale_product_a496ed_idx'),
        ),
    ]
