# Generated by Django 4.2 on 2025-02-02 09:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsaleline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
    ]
