# Generated by Django 4.2 on 2025-03-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("return_sales", "0003_returnsaleline_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnsaleline",
            name="date",
        ),
        migrations.AddField(
            model_name="returnsaleorder",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
