# Generated by Django 4.2 on 2025-03-15 00:29

from django.db import migrations
from django.utils.timezone import localtime


def update_return_sale_order_date(apps, schema_editor):
    ReturnSaleOrder = apps.get_model("return_sales", "ReturnSaleOrder")
    for instance in ReturnSaleOrder.objects.filter(date__isnull=True):
        instance.date = localtime(instance.created_at).date()
        instance.save(update_fields=["date"])


class Migration(migrations.Migration):

    dependencies = [
        ("return_sales", "0004_remove_returnsaleline_date_returnsaleorder_date"),
    ]

    operations = [
        migrations.RunPython(update_return_sale_order_date),
    ]
