# Generated by Django 4.2 on 2026-02-15 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('return_sales', '0007_alter_returnsaleline_average_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsaleorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnsaleorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='returnsaleorder',
            index=models.Index(fields=['created_by'], name='return_sale_created_1f299e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsaleorder',
            index=models.Index(fields=['updated_by'], name='return_sale_updated_71347a_idx'),
        ),
    ]
