# Generated by Django 4.2 on 2024-12-31 02:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('customer', '0005_customer_balance_customer_balance_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('sale', 'Sale')], default='payment', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='customer.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments', to='sales.saleorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer'], name='customer_pa_custome_5f111f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['type'], name='customer_pa_type_770055_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['created_at'], name='customer_pa_created_5c2e62_idx'),
        ),
    ]
