# Generated by Django 4.2 on 2025-01-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank_transfer')], default='cash', max_length=20),
        ),
    ]
