# Generated by Django 4.2 on 2025-01-12 21:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_payment', '0002_customerpayment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='new_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='old_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
    ]
