# Generated by Django 4.2 on 2025-01-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_payment', '0003_customerpayment_new_balance_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['amount'], name='customer_pa_amount_f84651_idx'),
        ),
    ]
