# Generated by Django 4.2 on 2025-01-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('return_sales', '0001_initial'),
        ('customer_payment', '0004_customerpayment_customer_pa_amount_f84651_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='return_sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_sale_payments', to='return_sales.returnsaleorder'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='type',
            field=models.CharField(choices=[('payment', 'Payment'), ('sale', 'Sale'), ('return_sale', 'Return_sale')], default='payment', max_length=20),
        ),
    ]
