# Generated by Django 4.2 on 2025-02-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('van', '0001_initial'),
        ('warehouse', '0008_remove_centralinventory_quantity'),
        ('product', '0003_product_average_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('transfer_type', models.CharField(choices=[('van_to_warehouse', 'Van to Warehouse'), ('warehouse_to_van', 'Warehouse to Van'), ('warehouse_to_warehouse', 'Warehouse to Warehouse'), ('van_to_van', 'Van to Van')], max_length=30)),
                ('destination_van', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_van', to='van.van')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_warehouse', to='warehouse.warehouse')),
                ('source_van', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_van', to='van.van')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_warehouse', to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transfer.transfer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
