# Generated by Django 4.2 on 2025-03-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
