# Generated by Django 4.2 on 2025-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_transfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
