# Generated by Django 4.2 on 2025-04-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_transfer_reversed_from_alter_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
